name: Build Static GPG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl tar

      - name: Run GPG Build Script
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: List All Files After Build (Debug)
        run: |
          echo "Listing all files recursively..."
          find . -type f

      - name: Move GPG Binary to bin/
        run: |
          mkdir -p bin
          GPG_PATH=$(find . -type f -name "gpg" | head -n 1)
          echo "Found GPG binary at: $GPG_PATH"
          cp "$GPG_PATH" bin/gpg
          chmod +x bin/gpg

      - name: Upload Built GPG Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpg-static
          path: bin/gpg
