name: Build Static GPG

on:
  workflow_dispatch:  # Trigger manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl tar

      - name: Run GPG Build Script
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Create /bin Folder
        run: |
          mkdir -p bin
          cp gpg bin/gpg
          chmod +x bin/gpg

      - name: Upload Built Binary to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gpg-static
          path: bin/gpg
